In [2]:
from pathlib import Path
import json
import numpy as np
import pandas as pd

DATA_DIR = Path("data")

def find_file(stem_or_name):
    """
    Finds a file inside DATA_DIR even if extension is missing in the name.
    Example: find_file("build_info") can find build_info.json.
    """
    direct = DATA_DIR / stem_or_name
    if direct.exists():
        return direct
    
    matches = list(DATA_DIR.glob(stem_or_name + ".*"))
    if matches:
        return matches[0]
    
    raise FileNotFoundError(f"Could not find {stem_or_name} in {DATA_DIR.resolve()}")

print("Data folder:", DATA_DIR.resolve())
print("Top-level files/folders:")
for p in DATA_DIR.iterdir():
    print("-", p.name)

Data folder: /workspaces/Project/data
Top-level files/folders:
- original_dataset_windows.xlsx
- rawdata
- build_info.json
- data_final
- scene_index_10s.csv
- split_index.csv
- stats.npz


In [3]:
build_info_path = find_file("build_info")

print("File:", build_info_path)

with open(build_info_path, "r", encoding="utf-8") as f:
    build_info = json.load(f)

build_info

File: data/build_info.json


{'dataset_root': 'C:\\Users\\BILAB\\Desktop\\User_data\\Traj\\agentformer_nusense\\processed_10s_cleaned_data_20260428_5hz',
 'target_hz': 5.0,
 'obs_seconds': 2.0,
 'future_seconds': 5.0,
 'workbook': 'C:\\Users\\BILAB\\Desktop\\User_data\\Traj\\agentformer_nusense\\original_dataset_windows.xlsx',
 'limit_scenes': None,
 'split_counts': {'train': 11626, 'val': 1148, 'test': 1131}}

In [4]:
windows_path = find_file("original_dataset_windows")

print("File:", windows_path)

if windows_path.suffix.lower() in [".xlsx", ".xls"]:
    original_dataset_windows = pd.read_excel(windows_path)
elif windows_path.suffix.lower() == ".csv":
    original_dataset_windows = pd.read_csv(windows_path)
else:
    raise ValueError(f"Unsupported file type: {windows_path.suffix}")

print(original_dataset_windows.shape)
original_dataset_windows.head()

File: data/original_dataset_windows.xlsx
(594, 11)


,participant,scenario,wz,original_start_unix,original_end_unix,original_duration_s,original_start_s,original_end_s,chosen_start_s,chosen_end_s,note
0,P10,S1_normal,1,1.765554e+09,1.765554e+09,10.0,0,10.0,NaN,NaN,NaN
1,P10,S1_normal,2,1.765554e+09,1.765554e+09,10.0,0,10.0,NaN,NaN,NaN
2,P10,S1_normal,3,1.765554e+09,1.765554e+09,10.0,0,10.0,NaN,NaN,NaN
3,P10,S2_noWarning,1,1.765553e+09,1.765553e+09,17.0,0,17.0,5.0,18.0,NaN
4,P10,S2_noWarning,2,1.765553e+09,1.765553e+09,10.5,0,10.5,NaN,NaN,NaN


In [5]:
for col in original_dataset_windows.columns:
    print("\n" + "="*80)
    print("Column:", col)
    print("Number of unique values:", original_dataset_windows[col].nunique(dropna=False))
    print(original_dataset_windows[col].unique())


Column: participant
Number of unique values: 33
<StringArray>
['P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'P16', 'P17', 'P18', 'P19', 'P20',
 'P21', 'P22', 'P23', 'P24', 'P25', 'P26', 'P27', 'P28', 'P29',  'P2', 'P30',
 'P31', 'P32', 'P33', 'P34',  'P3',  'P4',  'P5',  'P6',  'P7',  'P8',  'P9']
Length: 33, dtype: str

Column: scenario
Number of unique values: 6
<StringArray>
['S1_normal', 'S2_noWarning', 'S3_rainy', 'S4_curve', 'S5_nighttime',
 'S6_truck']
Length: 6, dtype: str

Column: wz
Number of unique values: 3
[1 2 3]

Column: original_start_unix
Number of unique values: 594
[1.76555366e+09 1.76555368e+09 1.76555370e+09 1.76555307e+09
 1.76555312e+09 1.76555315e+09 1.76555410e+09 1.76555423e+09
 1.76555426e+09 1.76555450e+09 1.76555453e+09 1.76555458e+09
 1.76555492e+09 1.76555494e+09 1.76555497e+09 1.76555528e+09
 1.76555532e+09 1.76555537e+09 1.76556069e+09 1.76556071e+09
 1.76556073e+09 1.76556032e+09 1.76556036e+09 1.76556039e+09
 1.76556114e+09 1.76556118e+09 1.76556122e+09

In [6]:
scene_index_path = DATA_DIR / "scene_index_10s.csv"

scene_index_10s = pd.read_csv(scene_index_path)

print(scene_index_10s.shape)
scene_index_10s.head()

(594, 16)


,participant,scenario,wz,n_frames,has_ego,has_worker,t_start_unix,t_end_unix,txt_path,rich_path,target_hz,source_original_start_unix,source_original_end_unix,chosen_start_s,chosen_end_s,note
0,P10,S1_normal,1,51,1,1,1.765554e+09,1.765554e+09,NaN,_rich\P10_S1_normal_WZ1.csv,5.0,1.765554e+09,1.765554e+09,NaN,NaN,NaN
1,P10,S1_normal,2,51,1,1,1.765554e+09,1.765554e+09,NaN,_rich\P10_S1_normal_WZ2.csv,5.0,1.765554e+09,1.765554e+09,NaN,NaN,NaN
2,P10,S1_normal,3,51,1,1,1.765554e+09,1.765554e+09,NaN,_rich\P10_S1_normal_WZ3.csv,5.0,1.765554e+09,1.765554e+09,NaN,NaN,NaN
3,P10,S2_noWarning,1,66,1,1,1.765553e+09,1.765553e+09,NaN,_rich\P10_S2_noWarning_WZ1.csv,5.0,1.765553e+09,1.765553e+09,5.0,18.0,NaN
4,P10,S2_noWarning,2,53,1,1,1.765553e+09,1.765553e+09,NaN,_rich\P10_S2_noWarning_WZ2.csv,5.0,1.765553e+09,1.765553e+09,NaN,NaN,NaN


In [7]:
for col in scene_index_10s.columns:
    print("\n" + "="*80)
    print("Column:", col)
    print("Number of unique values:", scene_index_10s[col].nunique(dropna=False))
    print(scene_index_10s[col].unique())


Column: participant
Number of unique values: 33
<StringArray>
['P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'P16', 'P17', 'P18', 'P19', 'P20',
 'P21', 'P22', 'P23', 'P24', 'P25', 'P26', 'P27', 'P28', 'P29',  'P2', 'P30',
 'P31', 'P32', 'P33', 'P34',  'P3',  'P4',  'P5',  'P6',  'P7',  'P8',  'P9']
Length: 33, dtype: str

Column: scenario
Number of unique values: 6
<StringArray>
['S1_normal', 'S2_noWarning', 'S3_rainy', 'S4_curve', 'S5_nighttime',
 'S6_truck']
Length: 6, dtype: str

Column: wz
Number of unique values: 3
[1 2 3]

Column: n_frames
Number of unique values: 37
[ 51  66  53  48  46  98  68  71  61  78  36  41  56  43  58  63  86  33
  38  96 143  76  73 101  83 116  81 106 111 108 131  88 113  91 118  31
 103]

Column: has_ego
Number of unique values: 1
[1]

Column: has_worker
Number of unique values: 1
[1]

Column: t_start_unix
Number of unique values: 594
[1.76555366e+09 1.76555368e+09 1.76555370e+09 1.76555308e+09
 1.76555312e+09 1.76555315e+09 1.76555410e+09 1.76555423e+09

In [8]:
split_index_path = DATA_DIR / "split_index.csv"

split_index = pd.read_csv(split_index_path)

print(split_index.shape)
split_index.head()

(13905, 14)


,sample,participant,scenario,wz,obs_T,fut_T,t_anchor,t_min,t_max,n_seg_frames,n_gaze_rows,seg_dir,gaze_file,split
0,P10_S1_normal_WZ1_s0000,P10,S1_normal,1,10,25,1.765554e+09,1.765554e+09,1.765554e+09,68,68,aligned\P10_S1_normal_WZ1_s0000\seg,aligned\P10_S1_normal_WZ1_s0000\gaze.csv,train
1,P10_S1_normal_WZ1_s0001,P10,S1_normal,1,10,25,1.765554e+09,1.765554e+09,1.765554e+09,68,69,aligned\P10_S1_normal_WZ1_s0001\seg,aligned\P10_S1_normal_WZ1_s0001\gaze.csv,train
2,P10_S1_normal_WZ1_s0002,P10,S1_normal,1,10,25,1.765554e+09,1.765554e+09,1.765554e+09,68,68,aligned\P10_S1_normal_WZ1_s0002\seg,aligned\P10_S1_normal_WZ1_s0002\gaze.csv,train
3,P10_S1_normal_WZ1_s0003,P10,S1_normal,1,10,25,1.765554e+09,1.765554e+09,1.765554e+09,68,68,aligned\P10_S1_normal_WZ1_s0003\seg,aligned\P10_S1_normal_WZ1_s0003\gaze.csv,train
4,P10_S1_normal_WZ1_s0004,P10,S1_normal,1,10,25,1.765554e+09,1.765554e+09,1.765554e+09,68,68,aligned\P10_S1_normal_WZ1_s0004\seg,aligned\P10_S1_normal_WZ1_s0004\gaze.csv,train


In [9]:
for col in split_index.columns:
    print("\n" + "="*80)
    print("Column:", col)
    print("Number of unique values:", split_index[col].nunique(dropna=False))
    print(split_index[col].unique())


Column: sample
Number of unique values: 13905
<StringArray>
['P10_S1_normal_WZ1_s0000', 'P10_S1_normal_WZ1_s0001',
 'P10_S1_normal_WZ1_s0002', 'P10_S1_normal_WZ1_s0003',
 'P10_S1_normal_WZ1_s0004', 'P10_S1_normal_WZ1_s0005',
 'P10_S1_normal_WZ1_s0006', 'P10_S1_normal_WZ1_s0007',
 'P10_S1_normal_WZ1_s0008', 'P10_S1_normal_WZ1_s0009',
 ...
   'P9_S6_truck_WZ3_s0002',   'P9_S6_truck_WZ3_s0003',
   'P9_S6_truck_WZ3_s0004',   'P9_S6_truck_WZ3_s0005',
   'P9_S6_truck_WZ3_s0006',   'P9_S6_truck_WZ3_s0007',
   'P9_S6_truck_WZ3_s0008',   'P9_S6_truck_WZ3_s0009',
   'P9_S6_truck_WZ3_s0010',   'P9_S6_truck_WZ3_s0011']
Length: 13905, dtype: str

Column: participant
Number of unique values: 33
<StringArray>
['P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'P16', 'P17', 'P18', 'P19', 'P20',
 'P21', 'P22', 'P23', 'P24', 'P25', 'P26', 'P27', 'P28', 'P29',  'P2', 'P30',
 'P31', 'P32', 'P33', 'P34',  'P3',  'P4',  'P5',  'P6',  'P7',  'P8',  'P9']
Length: 33, dtype: str

Column: scenario
Number of unique val

In [10]:
stats_path = DATA_DIR / "stats.npz"

stats = np.load(stats_path, allow_pickle=True)

print("Keys inside stats.npz:")
print(stats.files)

for key in stats.files:
    arr = stats[key]
    print("\nKey:", key)
    print("Shape:", arr.shape)
    print("Dtype:", arr.dtype)
    print("Preview:")
    print(arr[:5] if arr.ndim > 0 else arr)

Keys inside stats.npz:
['xy_scale', 'v_mean', 'v_std', 'a_mean', 'a_std', 'n_samples', 'eps_attn']

Key: xy_scale
Shape: ()
Dtype: float32
Preview:
50.0

Key: v_mean
Shape: (2,)
Dtype: float32
Preview:
[8.446403   0.35086685]

Key: v_std
Shape: (2,)
Dtype: float32
Preview:
[5.2026234 2.4204705]

Key: a_mean
Shape: (4,)
Dtype: float32
Preview:
[-5.0704203 -5.618188  -6.7843137 -6.5211864]

Key: a_std
Shape: (4,)
Dtype: float32
Preview:
[1.044049  1.2521594 1.7187133 2.2535257]

Key: n_samples
Shape: ()
Dtype: int64
Preview:
11626

Key: eps_attn
Shape: ()
Dtype: float32
Preview:
1e-09


In [11]:
rawdata_dir = DATA_DIR / "rawdata"

print("rawdata exists:", rawdata_dir.exists())
print("Files/folders inside rawdata:")

for p in sorted(rawdata_dir.iterdir())[:30]:
    print("-", p.name, "| folder" if p.is_dir() else "| file")

rawdata exists: True
Files/folders inside rawdata:
- WZ1 | folder
- WZ2 | folder
- WZ3 | folder


In [12]:
data_final_dir = DATA_DIR / "data_final"

print("data_final exists:", data_final_dir.exists())
print("Files/folders inside data_final:")

for p in sorted(data_final_dir.iterdir())[:30]:
    print("-", p.name, "| folder" if p.is_dir() else "| file")

data_final exists: True
Files/folders inside data_final:
- WZ1 | folder
- WZ2 | folder
- WZ3 | folder
- sample_manifest.csv | file


In [13]:
def preview_file(path, n=5):
    print("\n" + "=" * 80)
    print("File:", path)
    
    suffix = path.suffix.lower()
    
    try:
        if suffix == ".csv":
            df = pd.read_csv(path)
            print("Shape:", df.shape)
            display(df.head(n))
        
        elif suffix in [".xlsx", ".xls"]:
            df = pd.read_excel(path)
            print("Shape:", df.shape)
            display(df.head(n))
        
        elif suffix == ".json":
            with open(path, "r", encoding="utf-8") as f:
                obj = json.load(f)
            display(obj if isinstance(obj, dict) else obj[:n])
        
        elif suffix == ".npz":
            data = np.load(path, allow_pickle=True)
            print("Keys:", data.files)
            for key in data.files:
                arr = data[key]
                print(f"{key}: shape={arr.shape}, dtype={arr.dtype}")
                print(arr[:n] if arr.ndim > 0 else arr)
        
        else:
            print("Skipping unsupported type:", suffix)
    
    except Exception as e:
        print("Could not preview:", e)

supported_exts = {".csv", ".xlsx", ".xls", ".json", ".npz"}

for folder in [rawdata_dir, data_final_dir]:
    print("\n\n### Folder:", folder)
    files = [p for p in folder.rglob("*") if p.is_file() and p.suffix.lower() in supported_exts]
    print("Supported files found:", len(files))
    
    for p in files[:10]:
        preview_file(p)



### Folder: data/rawdata
Supported files found: 594

File: data/rawdata/WZ2/lap1/P7_S3_rainy_WZ2.csv
Shape: (86, 16)


,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.765395e+09,1,VEHICLE,287.4670,308.9990,0.0001,2.9156,12.3889,NaN,-0.076,0.393,0.0,NaN,NaN,False
1,0,1.765395e+09,2,PEDESTRIAN,231.2688,307.1827,1.6151,1.3942,NaN,NaN,NaN,NaN,NaN,-0.6016,-0.0105,False
2,1,1.765395e+09,1,VEHICLE,284.3798,309.5598,0.0001,2.9952,12.3056,-0.4167,-0.058,0.457,0.0,NaN,NaN,False
3,1,1.765395e+09,2,PEDESTRIAN,231.2580,307.1947,1.6220,1.2919,NaN,NaN,NaN,NaN,NaN,-0.5746,-0.0906,False
4,2,1.765395e+09,1,VEHICLE,282.9245,309.7471,-0.0000,3.0237,12.3056,0.0000,-0.040,0.469,0.0,NaN,NaN,False



File: data/rawdata/WZ2/lap1/P21_S4_curve_WZ2.csv
Shape: (102, 16)


,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.772053e+09,1,VEHICLE,-106.6670,-151.8096,0.0526,0.0092,5.6111,NaN,-0.0,0.150,0.0,NaN,NaN,False
1,0,1.772053e+09,2,PEDESTRIAN,-55.5319,-140.1874,1.0372,2.5025,NaN,NaN,NaN,NaN,NaN,-0.6229,-0.0682,False
2,1,1.772053e+09,1,VEHICLE,-105.9576,-151.8030,0.0529,0.0093,4.9722,-3.1944,-0.0,0.246,0.0,NaN,NaN,False
3,1,1.772053e+09,2,PEDESTRIAN,-55.5300,-140.1670,1.0277,2.4923,NaN,NaN,NaN,NaN,NaN,-0.6521,-0.0473,False
4,2,1.772053e+09,1,VEHICLE,-104.9081,-151.7931,0.0521,0.0094,4.5278,-2.2222,-0.0,0.460,0.0,NaN,NaN,False



File: data/rawdata/WZ2/lap1/P25_S3_rainy_WZ2.csv
Shape: (72, 16)


,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.772210e+09,1,VEHICLE,275.4479,310.2042,-0.0007,3.1037,9.4444,NaN,-0.012,0.541,0.0,NaN,NaN,False
1,0,1.772210e+09,2,PEDESTRIAN,229.5746,307.9645,1.0610,1.7324,NaN,NaN,NaN,NaN,NaN,-0.5974,-0.2014,False
2,1,1.772210e+09,1,VEHICLE,273.0291,310.2763,-0.0006,3.1141,9.7222,1.3889,-0.011,0.541,0.0,NaN,NaN,False
3,1,1.772210e+09,2,PEDESTRIAN,229.5728,307.9827,1.0098,1.6860,NaN,NaN,NaN,NaN,NaN,-0.6667,-0.2740,False
4,2,1.772210e+09,1,VEHICLE,270.9728,310.3181,-0.0007,3.1227,10.0000,1.3889,-0.011,0.541,0.0,NaN,NaN,False



File: data/rawdata/WZ2/lap1/P22_S4_curve_WZ2.csv
Shape: (212, 16)


,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.772060e+09,1,VEHICLE,-150.3681,-151.3521,0.0503,-0.0355,2.6667,NaN,-0.008,0.528,0.0,NaN,NaN,False
1,0,1.772060e+09,2,PEDESTRIAN,-56.4942,-140.2833,1.5507,-3.0458,NaN,NaN,NaN,NaN,NaN,-0.7414,0.1072,False
2,1,1.772060e+09,1,VEHICLE,-150.0625,-151.3615,0.0503,-0.0345,2.8056,0.6944,-0.008,0.528,0.0,NaN,NaN,False
3,1,1.772060e+09,2,PEDESTRIAN,-56.4253,-140.2587,1.5735,-3.0489,NaN,NaN,NaN,NaN,NaN,-0.6473,0.0979,False
4,2,1.772060e+09,1,VEHICLE,-149.3257,-151.3831,0.0503,-0.0322,3.1389,1.6667,-0.007,0.528,0.0,NaN,NaN,False



File: data/rawdata/WZ2/lap1/P18_S1_normal_WZ2.csv
Shape: (106, 16)


,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.771526e+09,1,VEHICLE,184.0266,-107.3514,0.2153,2.9593,1.1944,NaN,-0.109,0.000,0.0,NaN,NaN,False
1,0,1.771526e+09,2,PEDESTRIAN,77.3820,-106.4271,1.9315,3.0732,NaN,NaN,NaN,NaN,NaN,-0.1145,-0.0112,False
2,1,1.771526e+09,1,VEHICLE,183.9023,-107.3333,0.2149,2.9621,1.0278,-0.8333,-0.012,0.488,0.0,NaN,NaN,False
3,1,1.771526e+09,2,PEDESTRIAN,77.4196,-106.4575,1.9286,3.0419,NaN,NaN,NaN,NaN,NaN,-0.1023,-0.0225,False
4,2,1.771526e+09,1,VEHICLE,183.6750,-107.2940,0.2142,2.9628,1.1111,0.4167,-0.021,0.750,0.0,NaN,NaN,False



File: data/rawdata/WZ2/lap1/P5_S5_nighttime_WZ2.csv
Shape: (106, 16)


,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.765317e+09,1,VEHICLE,190.1466,-161.7096,0.2154,-1.5732,8.8611,NaN,0.001,0.400,0.0,NaN,NaN,False
1,0,1.765317e+09,2,PEDESTRIAN,189.3979,-219.4320,1.9815,1.5752,NaN,NaN,NaN,NaN,NaN,0.1796,-0.0382,False
2,1,1.765317e+09,1,VEHICLE,190.1403,-163.6732,0.2155,-1.5741,8.7778,-0.4167,0.001,0.451,0.0,NaN,NaN,False
3,1,1.765317e+09,2,PEDESTRIAN,189.4024,-219.4324,1.9862,1.6006,NaN,NaN,NaN,NaN,NaN,0.2201,-0.0639,False
4,2,1.765317e+09,1,VEHICLE,190.1328,-165.6303,0.2155,-1.5747,8.7778,0.0000,-0.001,0.469,0.0,NaN,NaN,False



File: data/rawdata/WZ2/lap1/P17_S2_noWarning_WZ2.csv
Shape: (106, 16)


,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.766001e+09,1,VEHICLE,-77.8135,-134.5256,-0.0063,-0.0875,7.9167,NaN,0.006,0.707,0.0,NaN,NaN,False
1,0,1.766001e+09,2,PEDESTRIAN,33.9981,-138.3908,1.0834,-1.7448,NaN,NaN,NaN,NaN,NaN,-1.0683,-0.1773,False
2,1,1.766001e+09,1,VEHICLE,-76.0510,-134.6867,-0.0060,-0.0913,8.5278,3.0556,0.007,0.711,0.0,NaN,NaN,False
3,1,1.766001e+09,2,PEDESTRIAN,34.0021,-138.4123,1.0219,-1.6444,NaN,NaN,NaN,NaN,NaN,-1.0758,-0.1246,False
4,2,1.766001e+09,1,VEHICLE,-73.9517,-134.8886,-0.0060,-0.0964,9.3889,4.3056,0.004,0.711,0.0,NaN,NaN,False



File: data/rawdata/WZ2/lap1/P13_S4_curve_WZ2.csv
Shape: (116, 16)


,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.765824e+09,1,VEHICLE,-129.7235,-150.1391,0.0357,0.0123,4.5000,NaN,0.011,0.75,0.0,NaN,NaN,False
1,0,1.765824e+09,2,PEDESTRIAN,-56.0611,-140.3528,1.6980,-3.0959,NaN,NaN,NaN,NaN,NaN,0.1478,-0.1110,False
2,1,1.765824e+09,1,VEHICLE,-128.6161,-150.1323,0.0309,0.0077,5.3056,4.0278,0.010,0.75,0.0,NaN,NaN,False
3,1,1.765824e+09,2,PEDESTRIAN,-56.0133,-140.3905,1.7102,2.9788,NaN,NaN,NaN,NaN,NaN,0.0976,-0.0871,False
4,2,1.765824e+09,1,VEHICLE,-127.3097,-150.1314,0.0310,0.0025,5.3056,0.0000,0.010,0.75,0.0,NaN,NaN,False



File: data/rawdata/WZ2/lap1/P21_S6_truck_WZ2.csv
Shape: (102, 16)


,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.772054e+09,1,VEHICLE,-62.7339,58.4700,-0.0049,-0.0009,12.3611,NaN,0.014,0.448,0.0,NaN,NaN,False
1,0,1.772054e+09,2,PEDESTRIAN,49.9725,57.3932,1.1324,1.0749,NaN,NaN,NaN,NaN,NaN,-0.0522,-0.0188,False
2,1,1.772054e+09,1,VEHICLE,-59.7679,58.4535,-0.0047,-0.0081,12.4167,0.2778,-0.012,0.443,0.0,NaN,NaN,False
3,1,1.772054e+09,2,PEDESTRIAN,49.9517,57.4109,1.1210,1.3507,NaN,NaN,NaN,NaN,NaN,-0.1395,-0.0211,False
4,2,1.772054e+09,1,VEHICLE,-58.1854,58.4515,-0.0047,-0.0014,12.4167,0.0000,-0.022,0.421,0.0,NaN,NaN,False



File: data/rawdata/WZ2/lap1/P8_S1_normal_WZ2.csv
Shape: (106, 16)


,frame,t_unix,agent_id,agent_type,pos_x,pos_y,pos_z,heading,speed_mps,delta_speed_mps2,steering,throttle,brake,pitch_rad,roll_rad,is_stopped
0,0,1.765483e+09,1,VEHICLE,177.1153,-109.2292,0.2135,3.0941,8.0278,NaN,-0.024,0.75,0.0,NaN,NaN,False
1,0,1.765483e+09,2,PEDESTRIAN,76.7684,-105.6211,1.3317,-1.8076,NaN,NaN,NaN,NaN,NaN,-1.1706,-0.6796,False
2,1,1.765483e+09,1,VEHICLE,175.2278,-109.1695,0.2137,3.1107,8.8611,4.1667,-0.024,0.75,0.0,NaN,NaN,False
3,1,1.765483e+09,2,PEDESTRIAN,76.7619,-105.6174,1.3658,-1.8153,NaN,NaN,NaN,NaN,NaN,-1.1455,-0.6631,False
4,2,1.765483e+09,1,VEHICLE,174.2360,-109.1501,0.2137,3.1195,9.3056,2.2222,-0.025,0.75,0.0,NaN,NaN,False




### Folder: data/data_final
Supported files found: 1

File: data/data_final/sample_manifest.csv
Shape: (13905, 7)


,file,scene_id,sample_idx,participant,scenario,wz,t_anchor
0,P10_S1_normal_WZ1_s0000.pkl,P10_S1_normal_WZ1,0,P10,S1_normal,1,1.765554e+09
1,P10_S1_normal_WZ1_s0001.pkl,P10_S1_normal_WZ1,1,P10,S1_normal,1,1.765554e+09
2,P10_S1_normal_WZ1_s0002.pkl,P10_S1_normal_WZ1,2,P10,S1_normal,1,1.765554e+09
3,P10_S1_normal_WZ1_s0003.pkl,P10_S1_normal_WZ1,3,P10,S1_normal,1,1.765554e+09
4,P10_S1_normal_WZ1_s0004.pkl,P10_S1_normal_WZ1,4,P10,S1_normal,1,1.765554e+09


In [14]:
from pathlib import Path
import pickle

DATA_DIR = Path("data")
pkl_files = list((DATA_DIR / "data_final").rglob("*.pkl"))

print("num pkl files:", len(pkl_files))
print("first pkl:", pkl_files[0])

with open(pkl_files[0], "rb") as f:
    sample = pickle.load(f)

print(type(sample))

if isinstance(sample, dict):
    print("keys:", sample.keys())
    for k, v in sample.items():
        print("\nKEY:", k)
        print("TYPE:", type(v))
        try:
            print("SHAPE:", v.shape)
        except:
            pass
        print("VALUE PREVIEW:", str(v)[:500])
else:
    print(sample)

num pkl files: 13905
first pkl: data/data_final/WZ2/lap1/P27_S2_noWarning_WZ2_s0003.pkl
<class 'dict'>
keys: dict_keys(['meta', 'ego_ref', 'agents', 'map'])

KEY: meta
TYPE: <class 'dict'>
VALUE PREVIEW: {'scene_id': 'P27_S2_noWarning_WZ2', 'sample_idx': 3, 't_anchor': 1772492700.929, 'participant': 'P27', 'scenario': 'S2_noWarning', 'wz': 2}

KEY: ego_ref
TYPE: <class 'dict'>
VALUE PREVIEW: {'pos_world': [-6.6113, -140.0374], 'heading_world': -0.0351}

KEY: agents
TYPE: <class 'dict'>
VALUE PREVIEW: {'ids': [1, 2, 'sumo_car_4'], 'types': ['VEHICLE', 'PEDESTRIAN', 'VEHICLE'], 'extents': array([[4.93, 1.91, 1.48],
       [0.5 , 0.5 , 1.8 ],
       [4.79, 1.85, 1.45]], dtype=float32), 'obs_xy': array([[[-2.5125530e+01, -8.2483310e-01],
        [ 3.9383110e+01,  3.3838475e+00],
        [ 2.2088141e+00, -5.2656996e-01]],

       [[-2.1122950e+01, -5.8592415e-01],
        [ 3.9305172e+01,  3.3693035e+00],
        [ 4.9660673e+00, -4.6825698e-01]],

       [[-1.7661251e+01, -4.1113585e-01],


In [15]:
from pathlib import Path
import pickle
import numpy as np

pkl_files = list(Path("data/data_final").rglob("*.pkl"))
p = pkl_files[0]

with open(p, "rb") as f:
    sample = pickle.load(f)

print("FILE:", p)

print("\nMETA:")
print(sample["meta"])

print("\nEGO_REF:")
print(sample["ego_ref"])

print("\nAGENTS KEYS:")
for k, v in sample["agents"].items():
    print("\nKEY:", k)
    print("TYPE:", type(v))
    if hasattr(v, "shape"):
        print("SHAPE:", v.shape)
        print("DTYPE:", v.dtype)
        print("PREVIEW:", v[:2] if v.ndim > 0 else v)
    else:
        print("VALUE:", v)

print("\nMAP KEYS:")
for k, v in sample["map"].items():
    print("\nKEY:", k)
    print("TYPE:", type(v))
    if hasattr(v, "shape"):
        print("SHAPE:", v.shape)
        print("DTYPE:", v.dtype)
    elif isinstance(v, list):
        print("LEN:", len(v))
        print("PREVIEW:", str(v[:2])[:800])
    else:
        print("VALUE:", str(v)[:800])

FILE: data/data_final/WZ2/lap1/P27_S2_noWarning_WZ2_s0003.pkl

META:
{'scene_id': 'P27_S2_noWarning_WZ2', 'sample_idx': 3, 't_anchor': 1772492700.929, 'participant': 'P27', 'scenario': 'S2_noWarning', 'wz': 2}

EGO_REF:
{'pos_world': [-6.6113, -140.0374], 'heading_world': -0.0351}

AGENTS KEYS:

KEY: ids
TYPE: <class 'list'>
VALUE: [1, 2, 'sumo_car_4']

KEY: types
TYPE: <class 'list'>
VALUE: ['VEHICLE', 'PEDESTRIAN', 'VEHICLE']

KEY: extents
TYPE: <class 'numpy.ndarray'>
SHAPE: (3, 3)
DTYPE: float32
PREVIEW: [[4.93 1.91 1.48]
 [0.5  0.5  1.8 ]]

KEY: obs_xy
TYPE: <class 'numpy.ndarray'>
SHAPE: (10, 3, 2)
DTYPE: float32
PREVIEW: [[[-25.12553     -0.8248331 ]
  [ 39.38311      3.3838475 ]
  [  2.2088141   -0.52656996]]

 [[-21.12295     -0.58592415]
  [ 39.305172     3.3693035 ]
  [  4.9660673   -0.46825698]]]

KEY: obs_heading
TYPE: <class 'numpy.ndarray'>
SHAPE: (10, 3)
DTYPE: float32
PREVIEW: [[ 0.0629     -2.2481      0.01136351]
 [ 0.0543     -2.2558      0.01991558]]

KEY: obs_spee